<a href="https://colab.research.google.com/github/11SyamSM/amikom/blob/main/NLP_Kelompok3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Tugas Kelompok (NLP - Natural Language Processing)**


Mata Kuliah : **Natural Language Processing (NLP)**<br/>
Dosen Pengampu : **Prof. Dr. Ema Utami, S.Si., M.Kom.**<br/>
Tutor : **Ainul Yaqin, M.Kom.**<br/>

---
***Anggota Kelompok 3***

22.55.2292 | Syamsul Syahab Mangun

22.55.2309 | Rizky Adi Nugroho

22.55.2323 | Fariz Zakaria

22.55.2343 | Elsina Novela Waroi


# A). Basic Text Processing 

##  1) Preparing Data

Data yang akan kami olah dalam Text Processing ini adalah data dari Twitter.

**Data Tweets** adalah kumpulan informasi yang terkait dengan tweet yang dihasilkan oleh pengguna Twitter. Informasi ini mencakup berbagai jenis data, termasuk teks tweet itu sendiri, tanggal dan waktu pembuatan tweet, lokasi pengguna yang memposting tweet, jumlah retweet dan like yang diterima tweet, hashtag yang digunakan, dan banyak lagi. 



Dalam melakukan pengumpulan data opini dari Twitter, kami menggunakan salah satu pustaka python yaitu SNScrape. Adapun alasan kami menggunakan SNScrape karena memiliki beberapa kelebihan, salah duanya adalah bisa menentukan waktu tweet yang diinginkan dan yang pasti tanpa ada limitasi penarikan data tweet (seperti Tweepy yang hanya mengijinkan 100 tweet per requestnya).

In [ ]:
!pip install snscrape

In [ ]:
import snscrape.modules.twitter as sntwitter
import pandas as pd

# Menentukan kata kunci pencarian
search_words = "psm makassar"

# Menentukan tanggal awal dan akhir pencarian
since_date = "2023-03-01"
until_date = "2023-03-31"

# Membuat query untuk pencarian tweet
query = f'{search_words} since:{since_date} until:{until_date}'

# Membuat list kosong untuk menyimpan tweet
tweets_list = []

# Mengumpulkan tweet dengan SNScrape
for i, tweet in enumerate(sntwitter.TwitterSearchScraper(query).get_items()):
    if i > 1000:  # Batasan jumlah tweet yang diambil
        break
    tweets_list.append([tweet.rawContent, tweet.user.username, tweet.date])

# Membuat dataframe dari list tweet
df_sns = pd.DataFrame(tweets_list, columns=['Tweet', 'Username', 'Datetime'])

# Menampilkan data tweet dalam Dataframe (5 data terakhir)
df_sns.tail()

Seperti yang ada pada output yang dihasilkan, pada perintah script ini kami melakukan beberapa hal:
- Menggunakan kata kunci (query) "PSM Makassar"
- Menentukan waktu tweet dari 01 Maret 2023 s/d 31 Maret 2023
- Mengambil 1000 sampel data tweet

##  2) Preprocessing

merupakan tahap awal dalam pengolahan teks atau data yang dilakukan sebelum data tersebut diolah lebih lanjut

### a) Ubah Ke Huruf Kecil

Salah satu teknik preprocessing yang umum dilakukan pada teks adalah mengubah seluruh karakter pada teks menjadi huruf kecil atau bisa disebut dengan lowercase.

Proses mengubah teks menjadi huruf kecil ini berguna untuk beberapa tujuan, antara lain:


*   memudahkan proses pemrosesan teks karena karakter menjadi seragam
*   membantu menghilangkan ambiguitas pada data
*   membuat proses pencarian dan pemrosesan teks lebih efisien dan akurat

berikut Proses mengubah seluruh huruf menjadi huruf kecil:

In [ ]:
df_sns['Tweet'] = df_sns['Tweet'].str.lower()
df_sns.tail()

### b) Hapus Tanda Baca

Proses menghapus tanda baca seperti titik, koma, dan lain-lain.

In [ ]:
import numpy as np

# Looping semua Tweet
new_tweet = []
for i in df_sns['Tweet']:
  # Hapus tanda baca menggunakan fungsi
  symbols = "!\"#$%&()*+-./:;<=>?@[\]^_`’'…{|}~\n"
  for j in range(len(symbols)):
      i = np.char.replace(i, symbols[j], ' ')
      i = np.char.replace(i, "  ", " ")
  i = np.char.replace(i, ',', '')
  new_tweet.append(i)

df_sns['Tweet'] = new_tweet
df_sns.tail()

Tweet      Username  \
996    psm makassar the ramang boys get ready to cha...    _thinkplus   
997    sahidsalahuddin psm makassar vipselatan thema...    Gozalimard   
998    psm makassar sambala kerenna verton no look pass      _ippangg   
999   kalau persib kalah pada pertandingan sore ini ...    agakarebaa   
1000  striker psm makassar ramadhan sananta sukses m...  detik_sulsel   

                      Datetime  
996  2023-03-20 05:37:27+00:00  
997  2023-03-20 05:22:08+00:00  
998  2023-03-20 05:18:50+00:00  
999  2023-03-20 04:52:53+00:00  
1000 2023-03-20 04:41:39+00:00

### c) Hapus Stopwords

Stopwords merupakan kata-kata yang sangat umum digunakan dalam suatu bahasa dan dianggap tidak memiliki makna penting dalam konteks pemrosesan teks.

Karena kami menggunakan tweet yang berbahasa indonesia, Untuk menghapus Stopword, maka kami menggunakan library dari Sastrawi.

Sastrawi sendiri merupakan sebuah library yang digunakan untuk melakukan proses stemming bahasa Indonseia.

In [ ]:
!pip install sastrawi

from Sastrawi.StopWordRemover.StopWordRemoverFactory import StopWordRemoverFactory
from Sastrawi.Stemmer.StemmerFactory import StemmerFactory

import nltk
from nltk.tokenize import word_tokenize
nltk.download('punkt')

In [ ]:
def hapus_stopwords(data):
    stop_words = StopWordRemoverFactory().get_stop_words()
    words = word_tokenize(str(data))
    new_text = ""
    for w in words:
        if w not in stop_words and len(w) > 1:
            new_text = new_text + " " + w
    return new_text

# Looping semua Tweet
new_tweet = []
for i in df_sns['Tweet']:
    # Ubah jadi huruf kecil
    new_tweet.append(hapus_stopwords(i))

df_sns['Tweet'] = new_tweet
df_sns.tail()

Tweet      Username  \
996    psm makassar the ramang boys get ready to cha...    _thinkplus   
997    sahidsalahuddin psm makassar vipselatan thema...    Gozalimard   
998    psm makassar sambala kerenna verton no look pass      _ippangg   
999    kalau persib kalah pertandingan sore psm maka...    agakarebaa   
1000   striker psm makassar ramadhan sananta sukses ...  detik_sulsel   

                      Datetime  
996  2023-03-20 05:37:27+00:00  
997  2023-03-20 05:22:08+00:00  
998  2023-03-20 05:18:50+00:00  
999  2023-03-20 04:52:53+00:00  
1000 2023-03-20 04:41:39+00:00

### d) Lemmatisasi

lemmatisasi digunakan untuk memperoleh kata dasar yang tepat sehingga bisa memperbaiki kualitas hasil pemrosesan teks

In [ ]:
def stemming(data):
    stemmer = StemmerFactory().create_stemmer()
    tokens = word_tokenize(str(data))
    new_text = ""
    for w in tokens:
        new_text = new_text + " " + stemmer.stem(w)
    return new_text

new_tweet = []
for i in df_sns['Tweet']:
  new_tweet.append(stemming(i))

df_sns['Tweet'] = new_tweet
df_sns.tail()

Tweet      Username  \
996    psm makassar the ramang boys get ready to cha...    _thinkplus   
997    sahidsalahuddin psm makassar vipselatan thema...    Gozalimard   
998    psm makassar sambala kerenna verton no look pass      _ippangg   
999    kalau persib kalah tanding sore psm makassar ...    agakarebaa   
1000   striker psm makassar ramadhan sananta sukses ...  detik_sulsel   

                      Datetime  Sentimen  Confidence  
996  2023-03-20 05:37:27+00:00  Positive      0.3612  
997  2023-03-20 05:22:08+00:00   Neutral      0.0000  
998  2023-03-20 05:18:50+00:00  Negative     -0.2960  
999  2023-03-20 04:52:53+00:00  Negative     -0.3612  
1000 2023-03-20 04:41:39+00:00  Positive      0.3818

## 4) Visualisasi Sentiment

Data sentimen adalah data yang menggambarkan perasaan, pendapat, atau sikap seseorang terhadap suatu topik atau objek tertentu, disini kami memasukkan ke dalam library Matplotlib.

In [ ]:
import matplotlib.pyplot as plt

from nltk.sentiment.vader import SentimentIntensityAnalyzer
nltk.download('vader_lexicon')

In [ ]:
def score_to_sentiment(score):
    if score > 0.2:
        return "Positive"
    elif score < -0.2:
        return "Negative"
    else:
        return "Neutral"

analyzer = SentimentIntensityAnalyzer()

confidence = []
for i in df_sns['Tweet']:
    confidence.append(analyzer.polarity_scores(str(i))['compound'])

sentimen = []
for i in df_sns['Tweet']:
    sentimen.append(score_to_sentiment(analyzer.polarity_scores(str(i))['compound']))

df_sns['Confidence'] = confidence
df_sns['Sentimen'] = sentimen
df_sns.head()

Tweet      Username  \
0   prediksi madura united fc vs psm makassar kun...    heraldindo   
1   psm makassar yemeni ciceng mennang na yala ju...   atekkempire   
2                psm makassar semoga aamiin ewakoooo    ulla_van17   
3   selamat pagi semoga menjadi jumat penuh berka...  PSM_Makassar   
4   ribuan suporter psm makassar belasan kelompok...  lagilagibola   

                   Datetime  Sentimen  Confidence  
0 2023-03-30 23:59:50+00:00  Positive      0.4215  
1 2023-03-30 23:47:44+00:00   Neutral      0.0000  
2 2023-03-30 23:39:29+00:00   Neutral      0.0000  
3 2023-03-30 23:38:49+00:00   Neutral      0.0000  
4 2023-03-30 23:37:55+00:00  Positive      0.6808

# B) Document Term of Matrix

Pada tahap ini, kami akan membuat sebuah tabel hasil berisi kata beserta jumlah frekuensi penggunaan kata.

### a) Tokenisasi

Tokenisasi atau tokenization adalah proses mengubah teks menjadi unit-unit yang lebih kecil yang disebut token.

tokenisasi sering dilakukan dengan memisahkan teks menjadi kata-kata atau tanda baca menggunakan whitespace, tanda baca, atau karakter tertentu sebagai pemisah.

In [ ]:
tokenized_text = []
text_column = df_sns['Tweet']
for text in text_column:
    tokens = word_tokenize(text)
    tokenized_text.append(tokens)

token = pd.DataFrame({'Token': tokenized_text})
token.tail()

### b) DToM

DToM merupakan singkatan dari Document-Term Matrix, yaitu representasi matematis dari dokumen teks yang digunakan dalam pemrosesan teks. DToM menggambarkan dokumen teks sebagai matriks yang terdiri dari baris dan kolom, di mana baris merepresentasikan dokumen dan kolom merepresentasikan kata-kata dalam dokumen tersebut.

In [ ]:
from collections import Counter

word = sorted(set(sum(tokenized_text, [])))
dtm = np.zeros((len(tokenized_text), len(word)))

for i, tokens in enumerate(tokenized_text):
    for token in tokens:
        j = word.index(token)
        dtm[i, j] += 1

df_dtm = pd.DataFrame(dtm, columns=word)

count = Counter(np.concatenate(tokenized_text, axis=0))

frekuensi = pd.DataFrame.from_dict(count, orient='index', columns=['Frekuensi'])
frekuensi.index.name = 'Token'
frekuensi

Frekuensi
Token                
prediksi            9
madura             93
united             97
fc                 25
vs                 44
...               ...
pass                1
facto               1
jure                1
menembus            1
pc3l0qbe9i          1

[4021 rows x 1 columns]

# C). Text Classification

### 1) Preparing Data

Dalam hal ini, kami melakukan persiapan data tweet yang sudah kami oleh untuk digunakan pada proses Text Classification ini.

#### a) Variabel Prediktor

Kami buat variabel prediktor sebagai X yang berisi informasi Tweet.

In [ ]:
X = df_sns.iloc[:, :1].values
X = X[:, 0]

#### b) Variabel Target

Variabel target dibuat sebagai y berisi sentimen.

In [ ]:
y = df_sns.iloc[:, 3].values  

### 2) k-Nearest Neighbors

**Pembagian Dataset**

Dimana kami membagi data tweet menjadi training dan data uji. Dalam hal ini persentasenya adalah 80% data training dan 20% data uji.

In [ ]:
nltk.download('stopwords')  
from nltk.corpus import stopwords  
from sklearn.feature_extraction.text import TfidfVectorizer  
tfidfconverter = TfidfVectorizer(max_features=2000, min_df=5, max_df=0.7, stop_words=stopwords.words('english'))  
X = tfidfconverter.fit_transform(df_sns['Tweet']).toarray()
 
from sklearn.model_selection import train_test_split  
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

**Normalisasi**

In [ ]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(X_train)

X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)

**Pembuatan Model KNN**

In [ ]:
from sklearn.neighbors import KNeighborsClassifier

classifier = KNeighborsClassifier(n_neighbors=5)
classifier.fit(X_train, y_train)

**Confusion Matrix**

In [ ]:
from sklearn.metrics import confusion_matrix

predictions = classifier.predict(X_test)

print("The Confusion Matrix is:\n")
print(confusion_matrix(y_test,predictions))

The Confusion Matrix is:

[[  2   8   0]
 [  0 165   0]
 [  0  20   6]]


**Menghitung Akurasi**

In [ ]:
from sklearn.metrics import classification_report, accuracy_score

print("Laporan Klasifikasi\n")
print(classification_report(y_test,predictions))
print("========\nAkurasi =", accuracy_score(y_test, predictions))  

Laporan Klasifikasi

              precision    recall  f1-score   support

    Negative       1.00      0.20      0.33        10
     Neutral       0.85      1.00      0.92       165
    Positive       1.00      0.23      0.38        26

    accuracy                           0.86       201
   macro avg       0.95      0.48      0.54       201
weighted avg       0.88      0.86      0.82       201

Akurasi = 0.8606965174129353


### 3) Random Forest

**Pembuatan Model Random Forest**

In [ ]:
from sklearn.ensemble import RandomForestClassifier
text_classifier = RandomForestClassifier(n_estimators=100, random_state=0)  
text_classifier.fit(X_train, y_train)

RandomForestClassifier(random_state=0)

**Confusion Matrix**

In [ ]:
from sklearn.metrics import confusion_matrix
predictions = text_classifier.predict(X_test)

print("The Confusion Matrix is:")
print(confusion_matrix(y_test,predictions)) 

The Confusion Matrix is:
[[  2   8   0]
 [  0 165   0]
 [  0  10  16]]


In [ ]:
from sklearn.metrics import classification_report, accuracy_score

print("Laporan Klasifikasi\n")
print(classification_report(y_test,predictions))
print("========\nAkurasi =", accuracy_score(y_test, predictions))  

Laporan Klasifikasi

              precision    recall  f1-score   support

    Negative       1.00      0.20      0.33        10
     Neutral       0.90      1.00      0.95       165
    Positive       1.00      0.62      0.76        26

    accuracy                           0.91       201
   macro avg       0.97      0.61      0.68       201
weighted avg       0.92      0.91      0.89       201

Akurasi = 0.9104477611940298
